#!/usr/bin/env python3
# ps5-native-app-boilerplate - Builds the subtitle font from Inter SemiBold.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes src/iptv_subtitle_font.h: Inter SemiBold glyphs as 8-bit coverage bitmaps at one size,
for Latin (with the accented letters of most European languages), Greek, Cyrillic and common
punctuation. The player scales them to the frame. Runs of zero coverage are stored as a zero and
a count, which roughly halves the data.

Needs Pillow and fontTools (pip install pillow fonttools). Usage: tools/generate-subtitle-font.py [output]
(run from the repository root)
"""
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "tools/fonts/Inter-SemiBold.ttf"
SIZE = 56

RANGES = (
    (0x0020, 0x007E),
    (0x00A0, 0x017F),  # Latin-1 Supplement and Latin Extended-A
    (0x0192, 0x0192),
    (0x0218, 0x021B),  # Romanian
    (0x0386, 0x03CE),  # Greek
    (0x0400, 0x045F),  # Cyrillic
    (0x2010, 0x2027),  # dashes, quotes, ellipsis
    (0x2030, 0x2030),
    (0x2039, 0x203A),
    (0x20AC, 0x20AC),
    (0x2122, 0x2122),
    (0x266A, 0x266B),  # music notes
)


def encode(data):
    """Zero runs become (0, count); other bytes are stored as they are."""
    out = bytearray()
    index = 0
    while index < len(data):
        if data[index] == 0:
            run = 1
            while index + run < len(data) and data[index + run] == 0 and run < 255:
                run += 1
            out += bytes((0, run))
            index += run
        else:
            out.append(data[index])
            index += 1
    return out


def main():
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src/iptv_subtitle_font.h"
    font = ImageFont.truetype(str(FONT), SIZE)
    ascent, descent = font.getmetrics()
    cmap = set(TTFont(str(FONT)).getBestCmap())

    glyphs, bitmap = [], bytearray()
    for first, last in RANGES:
        for code in range(first, last + 1):
            if code not in cmap:
                continue
            character = chr(code)
            mask, (x_offset, y_offset) = font.getmask2(character, mode="L")
            width, height = mask.size
            pixels = bytes(mask)
            if not any(pixels):
                width = height = 0
                pixels = b""
            advance = int(round(font.getlength(character)))
            glyphs.append((code, len(bitmap), width, height, x_offset, y_offset, advance))
            bitmap += pixels

    packed = encode(bitmap)
    lines = [
        "/* ProsperoTV - native PS5 IPTV client derived from ps5-native-app-boilerplate.",
        " * Copyright (C) 2026 BlackBearReloaded",
        " * SPDX-License-Identifier: GPL-3.0-or-later",
        " *",
        " * Generated by tools/generate-subtitle-font.py from tools/fonts/Inter-SemiBold.ttf",
        " * (SIL OFL 1.1; see tools/fonts/Inter-LICENSE.txt). Do not edit. */",
        "",
        "#ifndef IPTV_SUBTITLE_FONT_H",
        "#define IPTV_SUBTITLE_FONT_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct iptv_subtitle_glyph",
        "{",
        "    uint32_t code;",
        "    uint32_t offset; /* into the unpacked bitmap */",
        "    uint16_t width;",
        "    uint16_t height;",
        "    int16_t x_offset;",
        "    int16_t y_offset; /* from the top of the line */",
        "    uint16_t advance;",
        "} iptv_subtitle_glyph_t;",
        "",
        f"#define IPTV_SUBTITLE_FONT_SIZE {SIZE}u",
        f"#define IPTV_SUBTITLE_FONT_ASCENT {ascent}",
        f"#define IPTV_SUBTITLE_FONT_DESCENT {descent}",
        f"#define IPTV_SUBTITLE_FONT_GLYPHS {len(glyphs)}u",
        f"#define IPTV_SUBTITLE_FONT_BITMAP_BYTES {len(bitmap)}u",
        f"#define IPTV_SUBTITLE_FONT_PACKED_BYTES {len(packed)}u",
        "",
        "/* Sorted by code point. */",
        f"static const iptv_subtitle_glyph_t iptv_subtitle_glyphs[{len(glyphs)}] = {{",
    ]
    for glyph in glyphs:
        lines.append("    {0x%04x, %d, %d, %d, %d, %d, %d}," % glyph)
    lines.append("};")
    lines.append("")
    lines.append(f"static const uint8_t iptv_subtitle_font_packed[{len(packed)}] = {{")
    for start in range(0, len(packed), 32):
        lines.append("    " + ",".join(str(b) for b in packed[start:start + 32]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(glyphs)} glyphs, {len(bitmap)} bytes, {len(packed)} packed")


if __name__ == "__main__":
    main()
