#!/usr/bin/env python3
# ps5-native-app-boilerplate - Builds the player overlay's font from the bundled BMFont files.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes src/iptv_osd_font.h: anti-aliased Montserrat glyphs (ASCII 32-126) as 8-bit coverage
bitmaps, so the video presenter draws text without loading files at run time.

Usage: tools/generate-osd-font.py [output]   (run from the repository root)
"""
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "ui/fonts/lvgl-bitmap"
SIZES = (20, 28, 40)


def read_tga(path):
    data = path.read_bytes()
    id_length, colour_map, image_type = data[0], data[1], data[2]
    width = int.from_bytes(data[12:14], "little")
    height = int.from_bytes(data[14:16], "little")
    depth, descriptor = data[16], data[17]
    if colour_map or image_type != 2 or depth != 32:
        sys.exit(f"{path}: expected an uncompressed 32-bit TGA")
    pixels = data[18 + id_length:]
    top_down = bool(descriptor & 0x20)

    def alpha(x, y):
        row = y if top_down else height - 1 - y
        return pixels[(row * width + x) * 4 + 3]

    return width, height, alpha


def build(size):
    font = ElementTree.parse(FONTS / f"Montserrat-{size}.fnt").getroot()
    common = font.find("common")
    _, _, alpha = read_tga(FONTS / font.find("pages/page").get("file"))
    chars = {int(c.get("id")): c for c in font.find("chars")}
    glyphs, bitmap = [], bytearray()
    for code in range(32, 127):
        c = chars.get(code)
        if c is None:
            glyphs.append((0, 0, 0, 0, 0, 0))
            continue
        x, y = int(c.get("x")), int(c.get("y"))
        w, h = int(c.get("width")), int(c.get("height"))
        offset = len(bitmap)
        for row in range(h):
            for column in range(w):
                bitmap.append(alpha(x + column, y + row))
        glyphs.append((offset, w, h, int(c.get("xoffset")), int(c.get("yoffset")),
                       int(c.get("xadvance"))))
    return int(common.get("lineHeight")), int(common.get("base")), glyphs, bitmap


def main():
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src/iptv_osd_font.h"
    lines = [
        "/* ProsperoTV - native PS5 IPTV client derived from ps5-native-app-boilerplate.",
        " * Copyright (C) 2026 BlackBearReloaded",
        " * SPDX-License-Identifier: GPL-3.0-or-later",
        " *",
        " * Generated by tools/generate-osd-font.py from ui/fonts/lvgl-bitmap (Montserrat, SIL OFL",
        " * 1.1; see ui/fonts/lvgl-bitmap/OFL.txt). Do not edit. */",
        "",
        "#ifndef IPTV_OSD_FONT_H",
        "#define IPTV_OSD_FONT_H",
        "",
        '#include "iptv_osd.h"',
        "",
    ]
    names = []
    for size in SIZES:
        line_height, base, glyphs, bitmap = build(size)
        name = f"iptv_osd_montserrat_{size}"
        names.append(name)
        lines.append(f"static const uint8_t {name}_bitmap[{max(1, len(bitmap))}] = {{")
        for start in range(0, len(bitmap), 24):
            lines.append("    " + ", ".join(str(b) for b in bitmap[start:start + 24]) + ",")
        lines.append("};")
        lines.append(f"static const iptv_osd_glyph_t {name}_glyphs[95] = {{")
        for glyph in glyphs:
            lines.append("    {%d, %d, %d, %d, %d, %d, 0}," % glyph)
        lines.append("};")
        lines.append(f"static const iptv_osd_font_t {name} = {{{size}, {line_height}, {base}, "
                     f"{name}_glyphs, {name}_bitmap}};")
        lines.append("")
    lines.append("static const iptv_osd_font_t *const iptv_osd_fonts[] = {" +
                 ", ".join("&" + n for n in names) + "};")
    lines.append("")
    lines.append("#endif")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
